version: "3.8"
x-environment: &default-environment
  DATABASE_URL: postgres://postgres:${DB_PASSWORD}@postgres:5432/glitchtip
  SECRET_KEY: ${SECRET_KEY}
  PORT: 8000
  EMAIL_URL: smtp://172.17.0.1:25/?skip_ssl_verify=true&legacy_ssl=false&smtp_ssl_enabled=false&disable_starttls=true
  GLITCHTIP_DOMAIN: https://${DOMAIN}
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
  CELERY_WORKER_AUTOSCALE: "1,3" # Scale between 1 and 3 to prevent excessive memory usage. Change it or remove to set it to the number of cpu cores.
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "10000"

x-depends_on: &default-depends_on
  - postgres
  - redis

services:
  postgres:
    image: elestio/postgres:15
    restart: always
    environment:
      POSTGRES_DB: glitchtip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 172.17.0.1:34948:5432
  redis:
    image: elestio/redis:7.0
    command: --requirepass ${REDIS_PASSWORD}
  web:
    image: glitchtip/glitchtip
    restart: always
    depends_on: *default-depends_on
    ports:
      - "172.17.0.1:4024:8000"
    environment: *default-environment
    volumes:
      - ./uploads:/code/uploads
  worker:
    image: glitchtip/glitchtip
    restart: always
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    environment: *default-environment
    volumes:
      - ./uploads:/code/uploads
  migrate:
    image: glitchtip/glitchtip
    restart: always
    depends_on: *default-depends_on
    command: "./manage.py migrate"
    environment: *default-environment

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:38619:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
